### ISSUE TITLE
Wireframe edits

### ISSUE THREAD

**Issue by dcwebmaven** [CommerceDataService/BEA_RIMS_Redesign#25]
Edits to shopping cart wireframes

**Comment by radhikabhatt26** [comment]
- [x] Could you please send a mockup of the infographics you were thinking of including in step 2?  Explaining the difference between the two types of orders creates a lot of headaches here, so this page is really important.  A handwritten diagram, like the one we saw during the teleconference, would be just fine.
- [x] Is there enough clarity on how to proceed to checkout?  I was a little confused by this and limited by the wireframe.
- [x] Could we add a page that explains exactly what the customer will get before they add the order to their cart?
- [x] Will users have the option to also order customizable regions from a pull down menu as well as a map?  Many users order individual counties where they already know the name but not where it is located on a map.  Perhaps we could ask them if they would like to use a map to choose their area or use a pull-down, autofill list.
- [x] Will customers be able to make multiple selections and lasso items from the pull down lists? [yes, this is demonstrated in the original mockup]
- [x] For areas with multiple counties, can customers be given the option to name their region?
