### ISSUE TITLE
Infographics

### ISSUE THREAD

**Issue by dcwebmaven** [CommerceDataService/BEA_RIMS_Redesign#31]
Develop infographic for industry vs region and Regional infographic

**Comment by radhikabhatt26** [comment]
## Acceptance Criteria
- [x] Develop infographic for industry vs region
- [x] Receive Feedback from front end team
- [ ] Develop infographic for regional multipliers (outlining the differences btwn all the ordering options for region) --> waiting on response from Ian to create this infographic
